name: Update requirements
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - name: Set up Python 3.11
    uses: actions/setup-python@v4
    with:
      python-version: 3.11
  - name: Update requirements
    run: |
      pip install --requirement requirements/local_build.txt
      inv project.install-tools
      inv project.pip-compile --update
  - name: Generate token
    # Docs for action: https://github.com/marketplace/actions/github-app-token
    uses: tibdex/github-app-token@v1
    id: generate-token
    with:
      app_id: ${{ secrets.TOKEN_GENERATOR_APP_ID }}
      private_key: ${{ secrets.TOKEN_GENERATOR_PRIVATE_KEY }}
  - name: Create Pull Request
    # Docs for action: https://github.com/marketplace/actions/create-pull-request
    uses: peter-evans/create-pull-request@v4
    with:
      token: ${{ steps.generate-token.outputs.token }}
      commit-message: "[automated-commit] Update dependencies"
      title: Update dependencies
      body: Created by GitHub Actions
      base: develop
      labels: automated-pr
      branch: feature/update-dependencies
      delete-branch: true